### PR TITLE
Support for Apple TV and target

### PR DESCRIPTION
**Pull request by NSCabezon**

### CODE REVIEW

**Comment by Baglan** [comment]
Hi,

Thank you for submitting the pull request.

Could you tell me what is the essence of the change (all I see is a bunch of updated Xcode project files and auto–generated code).

**Comment by NSCabezon** [comment]
Hi, sorry I'm a bit new in pull requests, I was trying to get it to work on TV but I think the main reason it doesn't work is the pod spec, am I right?

**Comment by Baglan** [comment]
Cocoapods just help automating fetching the necessary files and adding them in your project. In this particular project only the files in the "Classes" folder are used.

I haven't used MCLocalization in an Apple TV project yet, could you tell me what is the problem with them? Some sort of compiler error?

**Comment by Baglan** [comment]
I've created a test tvOS project and, indeed, there was an issue with Podspec – turns out, an additional attribute had to be specified. Seems to be working now.

Thank you for pointing the problem out and please let me know if there are any more issues.

**Pull request closed without merging**
